version: '3.1'
services:
  react-app:
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true

